/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

package ebay.api.paypalapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.0
 * Fri Oct 28 15:24:09 ART 2011
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "urn:ebay:api:PayPalAPI", name = "PayPalAPIInterface")
@XmlSeeAlso({ebay.apis.eblbasecomponents.ObjectFactory.class, ObjectFactory.class, ebay.apis.enhanceddatatypes.ObjectFactory.class, ebay.apis.corecomponenttypes.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PayPalAPIInterface {

    @WebResult(name = "MassPayResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "MassPayResponse")
    @WebMethod(operationName = "MassPay")
    public MassPayResponseType massPay(
        @WebParam(partName = "MassPayRequest", name = "MassPayReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        MassPayReq massPayRequest
    );

    @WebResult(name = "BAUpdateResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "body")
    @WebMethod(operationName = "BillAgreementUpdate")
    public BAUpdateResponseType billAgreementUpdate(
        @WebParam(partName = "BillAgreementUpdateRequest", name = "BillAgreementUpdateReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BillAgreementUpdateReq billAgreementUpdateRequest
    );

    @WebResult(name = "EnterBoardingResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "EnterBoardingResponse")
    @WebMethod(operationName = "EnterBoarding")
    public EnterBoardingResponseType enterBoarding(
        @WebParam(partName = "EnterBoardingRequest", name = "EnterBoardingReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        EnterBoardingReq enterBoardingRequest
    );

    @WebResult(name = "CancelRecoupResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "CancelRecoupResponse")
    @WebMethod(operationName = "CancelRecoup")
    public CancelRecoupResponseType cancelRecoup(
        @WebParam(partName = "CancelRecoupRequest", name = "CancelRecoupReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        CancelRecoupReq cancelRecoupRequest
    );

    @WebResult(name = "GetBoardingDetailsResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "GetBoardingDetailsResponse")
    @WebMethod(operationName = "GetBoardingDetails")
    public GetBoardingDetailsResponseType getBoardingDetails(
        @WebParam(partName = "GetBoardingDetailsRequest", name = "GetBoardingDetailsReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        GetBoardingDetailsReq getBoardingDetailsRequest
    );

    @WebResult(name = "CreateMobilePaymentResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "CreateMobilePaymentResponse")
    @WebMethod(operationName = "CreateMobilePayment")
    public CreateMobilePaymentResponseType createMobilePayment(
        @WebParam(partName = "CreateMobilePaymentRequest", name = "CreateMobilePaymentReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        CreateMobilePaymentReq createMobilePaymentRequest
    );

    @WebResult(name = "RefundTransactionResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "RefundTransactionResponse")
    @WebMethod(operationName = "RefundTransaction")
    public RefundTransactionResponseType refundTransaction(
        @WebParam(partName = "RefundTransactionRequest", name = "RefundTransactionReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        RefundTransactionReq refundTransactionRequest
    );

    @WebResult(name = "BMSetInventoryResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BMSetInventoryResponse")
    @WebMethod(operationName = "BMSetInventory")
    public BMSetInventoryResponseType bmSetInventory(
        @WebParam(partName = "BMSetInventoryRequest", name = "BMSetInventoryReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BMSetInventoryReq bmSetInventoryRequest
    );

    @WebResult(name = "BMGetButtonDetailsResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BMGetButtonDetailsResponse")
    @WebMethod(operationName = "BMGetButtonDetails")
    public BMGetButtonDetailsResponseType bmGetButtonDetails(
        @WebParam(partName = "BMGetButtonDetailsRequest", name = "BMGetButtonDetailsReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BMGetButtonDetailsReq bmGetButtonDetailsRequest
    );

    @WebResult(name = "BMManageButtonStatusResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BMManageButtonStatusResponse")
    @WebMethod(operationName = "BMManageButtonStatus")
    public BMManageButtonStatusResponseType bmManageButtonStatus(
        @WebParam(partName = "BMManageButtonStatusRequest", name = "BMManageButtonStatusReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BMManageButtonStatusReq bmManageButtonStatusRequest
    );

    @WebResult(name = "DoMobileCheckoutPaymentResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "DoMobileCheckoutPaymentResponse")
    @WebMethod(operationName = "DoMobileCheckoutPayment")
    public DoMobileCheckoutPaymentResponseType doMobileCheckoutPayment(
        @WebParam(partName = "DoMobileCheckoutPaymentRequest", name = "DoMobileCheckoutPaymentReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        DoMobileCheckoutPaymentReq doMobileCheckoutPaymentRequest
    );

    @WebResult(name = "GetMobileStatusResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "GetMobileStatusResponse")
    @WebMethod(operationName = "GetMobileStatus")
    public GetMobileStatusResponseType getMobileStatus(
        @WebParam(partName = "GetMobileStatusRequest", name = "GetMobileStatusReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        GetMobileStatusReq getMobileStatusRequest
    );

    @WebResult(name = "BMCreateButtonResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BMCreateButtonResponse")
    @WebMethod(operationName = "BMCreateButton")
    public BMCreateButtonResponseType bmCreateButton(
        @WebParam(partName = "BMCreateButtonRequest", name = "BMCreateButtonReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BMCreateButtonReq bmCreateButtonRequest
    );

    @WebResult(name = "BillUserResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BillUserResponse")
    @WebMethod(operationName = "BillUser")
    public BillUserResponseType billUser(
        @WebParam(partName = "BillUserRequest", name = "BillUserReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BillUserReq billUserRequest
    );

    @WebResult(name = "GetPalDetailsResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "GetPalDetailsResponse")
    @WebMethod(operationName = "GetPalDetails")
    public GetPalDetailsResponseType getPalDetails(
        @WebParam(partName = "GetPalDetailsRequest", name = "GetPalDetailsReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        GetPalDetailsReq getPalDetailsRequest
    );

    @WebResult(name = "AddressVerifyResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "AddressVerifyResponse")
    @WebMethod(operationName = "AddressVerify")
    public AddressVerifyResponseType addressVerify(
        @WebParam(partName = "AddressVerifyRequest", name = "AddressVerifyReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        AddressVerifyReq addressVerifyRequest
    );

    @WebResult(name = "GetTransactionDetailsResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "GetTransactionDetailsResponse")
    @WebMethod(operationName = "GetTransactionDetails")
    public GetTransactionDetailsResponseType getTransactionDetails(
        @WebParam(partName = "GetTransactionDetailsRequest", name = "GetTransactionDetailsReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        GetTransactionDetailsReq getTransactionDetailsRequest
    );

    @WebResult(name = "GetBalanceResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "GetBalanceResponse")
    @WebMethod(operationName = "GetBalance")
    public GetBalanceResponseType getBalance(
        @WebParam(partName = "GetBalanceRequest", name = "GetBalanceReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        GetBalanceReq getBalanceRequest
    );

    @WebResult(name = "BMButtonSearchResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BMButtonSearchResponse")
    @WebMethod(operationName = "BMButtonSearch")
    public BMButtonSearchResponseType bmButtonSearch(
        @WebParam(partName = "BMButtonSearchRequest", name = "BMButtonSearchReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BMButtonSearchReq bmButtonSearchRequest
    );

    @WebResult(name = "SetMobileCheckoutResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "SetMobileCheckoutResponse")
    @WebMethod(operationName = "SetMobileCheckout")
    public SetMobileCheckoutResponseType setMobileCheckout(
        @WebParam(partName = "SetMobileCheckoutRequest", name = "SetMobileCheckoutReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        SetMobileCheckoutReq setMobileCheckoutRequest
    );

    @WebResult(name = "InitiateRecoupResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "InitiateRecoupResponse")
    @WebMethod(operationName = "InitiateRecoup")
    public InitiateRecoupResponseType initiateRecoup(
        @WebParam(partName = "InitiateRecoupRequest", name = "InitiateRecoupReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        InitiateRecoupReq initiateRecoupRequest
    );

    @WebResult(name = "BMUpdateButtonResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BMUpdateButtonResponse")
    @WebMethod(operationName = "BMUpdateButton")
    public BMUpdateButtonResponseType bmUpdateButton(
        @WebParam(partName = "BMUpdateButtonRequest", name = "BMUpdateButtonReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BMUpdateButtonReq bmUpdateButtonRequest
    );

    @WebResult(name = "TransactionSearchResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "TransactionSearchResponse")
    @WebMethod(operationName = "TransactionSearch")
    public TransactionSearchResponseType transactionSearch(
        @WebParam(partName = "TransactionSearchRequest", name = "TransactionSearchReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        TransactionSearchReq transactionSearchRequest
    );

    @WebResult(name = "BMGetInventoryResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "BMGetInventoryResponse")
    @WebMethod(operationName = "BMGetInventory")
    public BMGetInventoryResponseType bmGetInventory(
        @WebParam(partName = "BMGetInventoryRequest", name = "BMGetInventoryReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        BMGetInventoryReq bmGetInventoryRequest
    );

    @WebResult(name = "CompleteRecoupResponse", targetNamespace = "urn:ebay:api:PayPalAPI", partName = "CompleteRecoupResponse")
    @WebMethod(operationName = "CompleteRecoup")
    public CompleteRecoupResponseType completeRecoup(
        @WebParam(partName = "CompleteRecoupRequest", name = "CompleteRecoupReq", targetNamespace = "urn:ebay:api:PayPalAPI")
        CompleteRecoupReq completeRecoupRequest
    );
}
