= PayPal Connector Release Notes

:toc: macro
:toc-title: Contents:

:source-highlighter: prettify



:!numbered:

[green]#Community#

The PayPal Connector facilitates connections between Mule integration and PayPal. The PayPal Connector v3.0 allows you to perform any PayPal operations mentioned in https://developer.paypal.com/docs/classic/api/. The connector as of now only supports Signature API credential type of authentication.

*Contents*

toc::[]

== Version 3.0 - July 31, 2015

=== Version 3.0 Compatibility

The PayPal connector 3.0 is compatible with the following applications:


[cols="2*",width="50%",options="header"]
|===
| Application/Service | Version |

Mule Runtime	| 3.7.0 or later |
PayPal	| Classic SOAP API ver 2.0 |

|===

=== Version 3.0 Features

* Added support for all the standard operations and SOAP endpoints as per https://developer.paypal.com/docs/classic/api/. The limitation of usage of API is as per the PayPal account been used.
* Added support for Signature API credentials. The API Signature is infused into the SOAP header for every call.

This version of the connector uses a SOAP Connect feature in 3.7.0 and hence is not backward compatible with the earlier version of the connector.

=== Version 3.0 Fixes

None.

=== Version 3.0 Known Issues

As of now authentication is only supported via Signature API credentials. The Certificate API credentials is not supported. Please refer to https://developer.paypal.com/docs/classic/api/apiCredentials/ for more details.

== See Also

* Learn how to http://www.mulesoft.org/documentation/display/current/Installing+Connectors[Install and Configure Anypoint Connectors] in Anypoint Studio.

* Read more about this in http://mulesoft.github.com/paypal-connector/doc/user-manual.adoc and http://mulesoft.github.com/paypal-connector/demo for examples of how to use it
Access the http://forum.mulesoft.org/mulesoft[MuleSoft Forum] to pose questions and get help from Mule’s broad community of users.
