/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */

package org.mule.modules.paypal;

import org.mule.api.annotations.Config;
import org.mule.api.annotations.Connector;
import org.mule.modules.paypal.config.AbstractConfig;

/**
 * Mule Connector for PayPal.
 * 
 * <p>
 * PayPal is a service that enables you to pay, send
 * money, and accept payments without revealing your financial information.
 * </p>
 * <p>
 * PayPal acts like a digital wallet where you can securely store all your payment
 * options, such as your bank account and credit card. When you want to make a
 * payment, you don't have to pull out your credit card or type your billing info
 * every time. Simply click on the PayPal checkout button, log in to your PayPal
 * account, and select your preferred payment method. We'll complete the payment
 * process—without sharing your info with merchants and sellers.
 * </p>
 * @author MuleSoft, inc.
 */
@Connector(name = "paypal", schemaVersion = "1.0", friendlyName = "PayPal Connector", minMuleVersion = "3.7.0")
public class PayPalConnector {

    @Config
    AbstractConfig config;

    public AbstractConfig getConfig() {
        return config;
    }

    public void setConfig(AbstractConfig config) {
        this.config = config;
    }
}
